version: "3"
services:

  oj-redis:
    image: docker.m.daocloud.io/redis:4.0-alpine
    restart: always
    volumes:
      - ./data/redis:/data
    #for devoloment
    #ports:
    #  - "0.0.0.0:6379:6379"
    #for debug
    ports:
      - 6379:6379

  oj-postgres:
    image: docker.m.daocloud.io/postgres:10-alpine
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=onlinejudge
      - POSTGRES_USER=onlinejudge
      - POSTGRES_PASSWORD=onlinejudge
    #for devoloment
    #ports:
    #  - "0.0.0.0:5432:5432"
    #for debug
    ports:
      - 5432:5432
      
  #judge server，整合了judger
  oj-judge:
    image: registry.cn-hangzhou.aliyuncs.com/cqcet/oj-judge:1.6.1
    restart: always
    read_only: true
    cap_drop:
      - SETPCAP
      - MKNOD
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - FSETID
    tmpfs:
      - /tmp
    volumes:
      - ./data/backend/test_case:/test_case:ro
      - ./data/judge_server/log:/log
      - ./data/judge_server/run:/judger
    environment:
      - SERVICE_URL=http://oj-judge:8080
      - BACKEND_URL=http://oj-backend:8000/api/judge_server_heartbeat/
      - TOKEN=335fe12e208d95f03fa0bc403b9eb0bf
      # - judger_debug=1
  #web后端，Django
  oj-backend:
    image: registry.cn-hangzhou.aliyuncs.com/cqcet/oj-backend:2.4
    #绑定到本地的镜像
    #image: oj-image/backend:2.0
    restart: always
    depends_on:
      - oj-redis
      - oj-postgres
      - oj-judge
    volumes:
      - ./data/backend:/data
    environment:
      - POSTGRES_DB=onlinejudge
      - POSTGRES_USER=onlinejudge
      - POSTGRES_PASSWORD=onlinejudge
      - JUDGE_SERVER_TOKEN=335fe12e208d95f03fa0bc403b9eb0bf
      # - FORCE_HTTPS=1
      # - STATIC_CDN_HOST=cdn.oj.com
    ports:
      - "0.0.0.0:80:8000"
      - "0.0.0.0:443:1443"

  
  #测试用例的同步服务
  oj-rsync-master:
    image: registry.cn-hangzhou.aliyuncs.com/onlinejudge/oj_rsync
    container_name: oj-rsync-master
    volumes:
      - ./data/backend/test_case:/test_case:ro
      - ./data/rsync_master:/log
    environment:
      - RSYNC_MODE=master
      - RSYNC_USER=ojrsync
      - RSYNC_PASSWORD=ojrsync
    ports:
      - "0.0.0.0:873:873"